- codalab/apps/web/static/js/worksheet/contents_item_interface.js
- codalab/apps/web/static/js/worksheet/graph_item_interface.js
- codalab/apps/web/static/js/worksheet/html_item_interface.js
- codalab/apps/web/static/js/worksheet/image_item_interface.js
- codalab/apps/web/static/js/worksheet/markdown_item_interface.js
- codalab/apps/web/static/js/worksheet/record_item_interface.js
- codalab/apps/web/static/js/worksheet/table_item_interface.js
- codalab/apps/web/static/js/worksheet/worksheet_item_interface.js
- codalab/apps/web/static/js/worksheet/worksheet_items.js
- codalab/apps/web/templates/web/worksheets/detail.html
> Fix #47: Rename React worksheet classes to Items

- codalab/codalab/settings/__init__.py
>  #54: Generate website-config.json if none present

- .gitignore
> Add a .gitignore entry for files generated by Eclipse.

- codalab/apps/web/static/js/worksheet/graph_item_interface.js
@percyliang  
Although it's a one-line change, I actually spend hours figuring out a perfect solution. This one is so far the best, and we could talk in person. 
Thanks for reviewing!
> issue#43 fixed

- circle.yml
Was not generating website-config or database tables before. Now the (skeleton) tests should pass.
> Fixed latent issues with worksheets CircleCI

- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/templates/web/worksheets/detail.html
- codalab/apps/web/views.py
Fixes #89 
just realized we already removed jsxtransformer dependency, but maybe this is useful anyways?
@percyliang @andreweduffy please review
> Parse uuid from URL

- codalab/apps/web/templates/base.html
> Fix the help button.

- codalab/apps/web/static/js/worksheet/worksheet_item_interface.jsx
> fix issue #95

- codalab/apps/web/templates/web/worksheets/detail.html
@percyliang @ChengshuLi 
Please verify console errors are gone now.
> Remove source of console errors for jquery-editable-poshytip

- .gitignore
> Add .settings to .gitignore

- codalab/config/templates/bundle_server_config.json
- deployment/fabfile.py
> Adjust fabfile for after the user DB migration

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/bundle_uploader.jsx
- codalab/apps/web/static/js/worksheet/faq.jsx
- codalab/apps/web/static/js/worksheet/sample_worksheets_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_action_bar.jsx
- codalab/apps/web/static/js/worksheet/worksheet_chat_box.jsx
- codalab/apps/web/static/js/worksheet/worksheet_chat_portal.jsx
- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
See related https://github.com/codalab/codalab-cli/pull/394
@percyliang
> Fix the arbitrary handling of HTTP errors.

- codalab/apps/web/static/js/worksheet/new_worksheet.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
let the new worksheet button show up before the browser receives userIno from the server
@percyliang
> Fix new worksheet button 

- codalab/apps/web/static/js/worksheet/bundle_uploader.jsx
- codalab/apps/web/static/js/worksheet/button.jsx
- codalab/apps/web/static/js/worksheet/new_worksheet.jsx
- codalab/apps/web/static/js/worksheet/run_bundle_builder.jsx
- codalab/apps/web/static/less/button.less
- codalab/apps/web/static/less/worksheets.less
> change the style of three buttons

- codalab/apps/web/static/less/worksheets.less
> Issue #133: Make three buttons appear on the same line

- codalab/apps/web/static/js/worksheet/run_bundle_builder.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
- codalab/apps/web/static/less/worksheets.less
> Issue #130: cosmetic refinements to run button

- deployment/fabfile.py
See also https://github.com/codalab/codalab-cli/pull/412
@kashizui
> Auto create default clients.

- codalab/apps/web/templates/web/account/login.html
- codalab/apps/web/templates/web/account/reset.html
- codalab/apps/web/templates/web/account/reset_complete.html
- codalab/apps/web/templates/web/account/reset_sent.html
- codalab/apps/web/templates/web/account/reset_verified.html
- codalab/apps/web/urls/account.py
- codalab/apps/web/views.py
Must be merged after codalab/codalab-cli#416
@klopyrev
> Add password reset pages

- codalab/apps/web/static/js/account/account_profile.jsx
- codalab/apps/web/templates/web/account/changeemail.html
- codalab/apps/web/templates/web/account/changeemail_sent.html
- codalab/apps/web/templates/web/account/reset.html
- codalab/apps/web/templates/web/account/reset_complete.html
- codalab/apps/web/urls/account.py
- codalab/apps/web/views.py
- Add links from account profile page to change email and password 
- Add pages for changing email with warning messages
Must be merged after codalab/codalab-cli#420
@klopyrev
> Let users change email and password

- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_items.jsx
> Issue#151: avoid calling fetch twice when loading a worksheet

- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
> Issue #132: focus newly added bundles

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/table_item_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
> Rename the bundle contents blob method.

- codalab/apps/web/static/js/worksheet/new_worksheet.jsx
- codalab/apps/web/static/js/worksheet/worksheet_utils.jsx
> issue#167: add buildTerminalCommand, fix new worksheet noop

- codalab/apps/web/static/js/worksheet/editable_field.jsx
> Issue #177: fix worksheet-editable not showing worksheet title and name

- codalab/apps/web/static/js/worksheet/run_bundle_builder.jsx
> issue #160: Better command line printout for run bundle builder 

- codalab/apps/web/static/js/worksheet/editable_field.jsx
@percyliang 
This time it should be fixed. Sorry about this.
> Issue#184: fix empty worksheet title and name

- codalab/config/templates/bundle_server_config.json
> Clean up launch flag

- codalab/codalab/settings/__init__.py
- codalab/config/templates/bundle_server_config.json
- codalab/config/templates/supervisor.conf
- deployment/fabfile.py
> Set up automatic monitoring of wsprod and wstest.

- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
> Issue #194: fix focus on last bundle sometimes does not work

- codalab/apps/web/static/js/worksheet/editable_field.jsx
> Issue #192: fix empty title cannot be edited

- codalab/apps/web/templates/web/account/signup.html
This PR modifies the sign up form to ask for First Name, Last Name and Affiliation. First and last name fields are mandatory, while Affiliation is optional.
Fixes #200
> Accept user name and affiliation while sign up. Fixes #200.

- deployment/fabfile.py
Paired with PR codalab/codalab-cli#564
@percyliang
> Update configuration for admin notifications

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_items.jsx
fix #211 first bug
@percyliang
> Refresh worksheet when metadata is changed in bundle side panel

- codalab/config/templates/nginx.conf
- codalab/config/templates/supervisor.conf
> Update for REST server-only deployment

- codalab/apps/web/static/js/account/account_profile.jsx
- codalab/apps/web/static/js/worksheet/worksheet_utils.jsx
- codalab/apps/web/templates/web/account/profile.html
- codalab/apps/web/templates/web/account/signup.html
Fixes #215. Changes singup.html to add checkbox for whether user wants to be sent email notifications.
> Send notifications

- codalab/apps/web/static/js/worksheet/table_item_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_chat_box.jsx
- codalab/apps/web/static/js/worksheet/worksheet_help_button.jsx
- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/static/less/worksheets.less
- codalab/apps/web/templates/web/worksheets/detail.html
Issue: codalab/codalab-worksheets#251
Corresponding PR in codalab-worksheets: https://github.com/codalab/codalab-cli/pull/675#pullrequestreview-20198755
Creates a user workflow for sending support emails to CodaLab's support email address. You can view the UI at: http://138.197.208.207:8000/. (My deployment)
Some screenshots:
Initial state:
After clicking on the help button:
> Help button

- codalab/apps/web/static/js/worksheet/bundle_uploader.jsx
- codalab/apps/web/static/js/worksheet/new_worksheet.jsx
- codalab/apps/web/static/js/worksheet/run_bundle_builder.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
- codalab/apps/web/static/js/worksheet/worksheet_utils.jsx
- codalab/apps/web/static/less/button.less
I'm wondering if we should turn off the "New Worksheet" and "New Run" bundles as well. I also wonder if it would make more sense to leave the buttons there but redirect the user to the sign in page when they click on the buttons.
> if no user logged in, doesn't show upload button

- codalab/apps/web/static/js/worksheet/context_menu.jsx
- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
> shows context menu items based on permissioning

- codalab/codalab/settings/__init__.py
- templates/nginx
...to match the one pasted from max, modulo templating paths.
> Updated nginx config template
