codalab/codalab-worksheets

- codalab/requirements/common.txt
If mysql_config is not installed, this requirement breaks the setup script. MYSQL-Python should be installed as part of the MySQL setup.
@percyliang 
This commit fixes #59
> Don't require MYSQL-Python when setting up Worksheets.

- codalab/apps/web/static/js/worksheet/bundle_uploader.js
Fix issue #50. 
- Reset file input value so that if the user upload the same file again, onchange event will be triggered.
> fix issue #50 

- circle.yml
In reference to #48 
Truth is this won't be completely fixed until nosetests start working
again, and with the separation of Worksheets and Competitions it looks
like the Selenium tests are broken.
@percyliang
> "Fixed" CirclCI config

- codalab/codalab/settings/__init__.py
One way around this. 
Keep ADMINS as an empty list
It won't affect monitor.py because monitor.py is sending email to config['django']['admin-email'] rather than ADMINS.
> Stop error email notification from Django

- codalab/codalab/settings/__init__.py
- codalab/config/templates/nginx.conf
- codalab/manage
- deployment/fabfile.py
3 changes, specifically:
1) Get config_gen to run again locally (It was failing on SSL_CERTIFICATE|length).
2) Add the REST server reverse proxy rule.
3) Set up Nginx for local development. I'll add instructions to the Wiki once the code is checked in, but basically:
cl server
cl rest-server
cd codalab-worksheets/codalab
./manage runserver 127.0.0.1:2700
sudo apt-get install nginx
./manage config_gen
sudo cp config/generated/nginx.conf /etc/nginx/sites-enabled
sudo service nginx restart
@percyliang @kashizui @andreweduffy
> Set up Nginx for the REST api

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/bundle_uploader.jsx
- codalab/apps/web/static/js/worksheet/editable_field.jsx
- codalab/apps/web/static/js/worksheet/faq.jsx
- codalab/apps/web/static/js/worksheet/sample_worksheets_interface.jsx
- codalab/apps/web/static/js/worksheet/table_item_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_action_bar.jsx
- codalab/apps/web/static/js/worksheet/worksheet_chat_box.jsx
- codalab/apps/web/static/js/worksheet/worksheet_chat_portal.jsx
- codalab/apps/web/static/js/worksheet/worksheet_content.jsx
- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
- codalab/apps/web/templates/base.html
- codalab/apps/web/templates/web/bundles/detail.html
- codalab/apps/web/templates/web/index.html
- codalab/apps/web/templates/web/worksheets/detail.html
Update the Javascript app to use the migrated REST APIs. Now, Django doesn't talk to the Bundle Server at all, only the Javascript app does.
Note the css hack to get the correct things to display, depending on whether the user is logged in or not.
@kashizui @percyliang
> Point Javascript app at the new REST APIs.

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
Fix the display of symbolic links. It could be useful to see the symbolic link structure in a bundle.
I'm also fixing all the downloading code to disallow following these in case the user tries to download from one.
@percyliang
> Fix display of symbolic links

- codalab/requirements/common.txt
Remove unnecessary requirements. Both are no longer used. One causes an error during installation since it requires some other package on the system.
@kashizui
> Remove unnecessary requirements.

- codalab/apps/web/templates/web/account/verify_success.html
New behavior on verification success page:
- If user is already already signed in, show link to dashboard.
- If user is not yet signed in, show link to sign in page (with `next=` set to the dashboard).
Fixes #136 
@klopyrev
> Send user to right place after verifying account

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
- codalab/apps/web/static/less/worksheets.less
Improve how states are displayed. Specifically:
1) Move run_status and failure_message up to the header. run_status will only be shown if is something like "Downloading Docker Image".
2) Use the same orange color for created, staged, waiting_for_worker_startup, starting, running. Otherwise, it's hard to see since it is white on grey.
@percyliang
> Improve the display of various states.

- codalab/apps/web/static/css/jquery-editable.css
This PR modifies. `:hover` selector of certain editable classes - it has been granted the cursor type as `text` and dashed border of a blue shade for making it more intuitive.
Fixes #69.
> Text cursor and blue dashed border on hovering editable fields.

- codalab/config/templates/nginx.conf
Allows streaming uploads directly into our unzipping functions.
Fixes codalab/codalab-cli#599
References:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version
@percyliang
> Disable request buffering in nginx

- codalab/apps/web/static/js/worksheet/table_item_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_item_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_items.jsx
Issue: #244 
This code has been tested and does address the bug. Please refer to the issue for a description of the diagnosis and solution. A summary:
- The problem: When the worksheet page updates (after pulling the API for updates), worksheet_items renders once, table_items renders once, then worksheet_items renders a final time. Since Mousetrap uses the last binding command, worksheet_items' binding is executed, even though we want table_items' binding.
- The solution: The up and down key bindings from all of the files were moved into worksheet_interface.jsx, the parent of all of these classes. The original code key binding code was deleted. Now, when an up or down key event fires, it is caught in worksheet_interface, and depending on which item is in focus, the Worksheet's state is …
> Keyboard nav bug fix

- codalab/config/templates/supervisor.conf
Increases number of threads to 8 * 50 = 400.
This is within the `2-4 x $(NUM_CORES)` range specified in the Gunicorn documentation: http://docs.gunicorn.org/en/latest/settings.html#workers
Looking at wsprod with `htop` it looks like the REST server threads are quite lightweight so the memory impact shouldn't be a problem.
We will deploy this on wstest first to test it out.
Address #256
> Increase default num processes to 8

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
- codalab/apps/web/static/js/worksheet/worksheet_utils.jsx
Fixes the following issues relating to the worksheet sidebar:
- Permissions displaying as [Object object] for bundles and subworksheets
- Relevant issue: #274 - includes discussion of subworksheets
- Bundle's state in the worksheet is [Object object]
The fix for subworksheets required fetching new data. I chose to implement a "quick fix" that's based on the existing code for fetching bundle information. This way of fetching data is not the best way to do so in React because it does not clearly show direction of information flow from the user's click to populating the sidebar with data. The beginning of a better implementation is in the branch (max-fixes-sidebar)[https://github.com/codalab/codalab-worksheets/tree/max-fixes-sidebar]. It will take many more hours before that implementation …
> Fix sidebar problems

- codalab/apps/web/static/js/worksheet/contents_item_interface.jsx
Fixes #354 
The problem was that for content directives that didn't have the right path, the `interpreted` field was `null`, and there was no check in the code to see if it was not null. I simply added a check for `null` that would return an empty div element.
Question: What should be the expected behavior? I think the ideal would be to notify the user about the line with the invalid path, so I propose displaying an item that's simply an error message, saying something like: "0x5ab911b does not have path /output".
> fixes display content with bad path bug

- codalab/apps/web/static/js/worksheet/worksheet_side_panel.jsx
There was a bug in the code where, as a logged in user who didn't have permission to a worksheet, when you tried creating a new worksheet, there would be a null value that caused an error. Related to PR #357
> checks for null values

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
Even if the server responds with a 404, the file contents in the sidebar of a bundle should be empty.
> fixes stale contents in sidebar for staged bundles

- codalab/apps/web/static/js/worksheet/worksheet_interface.jsx
It's not clear to me why this fix works. I have reasons and tests to show that the correct behavior is being achieved. PRs. Please suggest other reasons / tests I can use. Plan of action: Since I don't have 100% confidence that the PR doesn't break anything, I'm thinking that I'll deploy both this change and my large search bar / user profile change to worksheets-dev and we'll really test it before deploying both 
fixes #330
Reasons why this fix works:
- This is the commit where the comment about the `escCount` hack was added: https://github.com/codalab/codalab-worksheets/commit/98fb9f1f6558458a97fbfa9bbd98d2400389ceaa. The purpose seems to be to manually trigger a re-render in some of some components (namely, of the New Worksheet Modal and the Worksheet Side Panel) whenever the "escape" …
> fixes escape key, inconsistent rendering

- codalab/apps/web/static/js/bundle/bundle_interface.jsx
Before: 
If you click on a finished run bundle, you would see the stdout of that bundle, for example "hello world". Then, if you clicked on a staged or created bundle, it would not remove the stdout "hello world", because the stdout and stderr state variables in the Bundle view were not getting removed. 
After: 
The stdout and stderr should properly disappear.
> Clear state properly for bundles without any bundle content

- codalab/apps/web/gulpfile.js
- codalab/apps/web/package.json
Adds new npm run command calls watch, which calls the gulp task watch. The gulp task runs the jsx and less compilation tasks whenever the relevant source files change.
> Adds 'npm run watch' command
